/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: operations["AppController_getHello"];
  };
  "/users": {
    get: operations["UsersController_findAll"];
    post: operations["UsersController_create"];
  };
  "/users/{id}": {
    get: operations["UsersController_findOne"];
    delete: operations["UsersController_remove"];
    patch: operations["UsersController_update"];
  };
}

export interface components {
  schemas: {
    CreateUserDto: { [key: string]: unknown };
    UpdateUserDto: { [key: string]: unknown };
  };
}

export interface operations {
  AppController_getHello: {
    parameters: {};
    responses: {
      200: unknown;
    };
  };
  UsersController_findAll: {
    parameters: {};
    responses: {
      200: unknown;
    };
  };
  UsersController_create: {
    parameters: {};
    responses: {
      201: unknown;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUserDto"];
      };
    };
  };
  UsersController_findOne: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: unknown;
    };
  };
  UsersController_remove: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: unknown;
    };
  };
  UsersController_update: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: unknown;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateUserDto"];
      };
    };
  };
}

export interface external {}
